Repository litecoin-foundation/litewallet-ios, pull requests merged in 2022-11, with the labels that each got.

#139 🚧[Techdebt] Firebase polish 121
  TodayExtension/BRTodayViewController.m
  loafwallet.xcodeproj/project.pbxproj
  loafwallet.xcworkspace/xcshareddata/swiftpm/Package.resolved
  loafwallet/BuyTableViewController.swift
  loafwallet/PartnerData.swift
  loafwallet/SupportSafariView.swift
  loafwallet/src/Constants/Constants.swift
  loafwallet/src/ModalPresenter.swift
  loafwallet/src/ViewControllers/AboutViewController.swift
  loafwallet/src/ViewControllers/RootModals/SendViewController.swift
Labels: tech debt

#147 Mark unused code
  loafwallet.xcodeproj/project.pbxproj
  loafwallet/PartnerData.swift
  unused.rb
Labels: tech debt

#150 🦟 [Bugfix] buy fixes 138
  loafwallet.xcodeproj/project.pbxproj
  loafwallet/src/Constants/Constants.swift
  loafwallet/src/Platform/BRAPIClient.swift
  loafwalletTests/Constants Tests/ConstantsTests.swift
Labels: bug

#154 Retired old https server code
  loafwallet.xcodeproj/project.pbxproj
  loafwallet/src/Platform/BRAPIProxy.swift
  loafwallet/src/Platform/BRCameraPlugin.swift
  loafwallet/src/Platform/BRGeoLocationPlugin.swift
  loafwallet/src/Platform/BRHTTPFileMiddleware.swift
  loafwallet/src/Platform/BRHTTPIndexMiddleware.swift
  loafwallet/src/Platform/BRHTTPRouter.swift
  loafwallet/src/Platform/BRHTTPServer.swift
  loafwallet/src/Platform/BRKVStorePlugin.swift
  loafwallet/src/Platform/BRWebSocket.swift
Labels: tech debt

#155 #148 TransactionsViewController crashfix
  loafwallet/TransactionsViewController.swift
Labels: bug, serious bug

#160 🚀[Release v3.10.1] Merge into Main
  .github/workflows/PubtoPrivate.yml
  .github/workflows/sync-mirror.yml
  TodayExtension/BRTodayViewController.m
  loafwallet.xcodeproj/project.pbxproj
  loafwallet.xcworkspace/xcshareddata/swiftpm/Package.resolved
  loafwallet/BuyTableViewController.swift
  loafwallet/PartnerData.swift
  loafwallet/SupportSafariView.swift
  loafwallet/TransactionsViewController.swift
  loafwallet/src/Constants/Constants.swift
  loafwallet/src/ModalPresenter.swift
  loafwallet/src/Platform/BRAPIClient.swift
  loafwallet/src/Platform/BRAPIProxy.swift
  loafwallet/src/Platform/BRCameraPlugin.swift
  loafwallet/src/Platform/BRGeoLocationPlugin.swift
  loafwallet/src/Platform/BRHTTPFileMiddleware.swift
  loafwallet/src/Platform/BRHTTPIndexMiddleware.swift
  loafwallet/src/Platform/BRHTTPRouter.swift
  loafwallet/src/Platform/BRHTTPServer.swift
  loafwallet/src/Platform/BRKVStorePlugin.swift
  loafwallet/src/Platform/BRWebSocket.swift
  loafwallet/src/ViewControllers/AboutViewController.swift
  loafwallet/src/ViewControllers/RootModals/SendViewController.swift
  loafwalletTests/Constants Tests/ConstantsTests.swift
  unused.rb
Labels: tech debt
