Repository litecoin-foundation/litewallet-ios, pull requests merged in 2024-12, with the labels that each got.

#259 🚀[Release v3.13.5] Merge into Main RESET
  litewallet.xcodeproj/project.pbxproj
  litewallet/BuyView.swift
  litewallet/SyncProgressHeaderView.swift
  litewalletTests/Legacy BRTests/BRReplicatedKVStoreTests.swift
Labels: 🚀 release

#260 ✨✨[Feature] Refresh seed words showing
  litewallet.xcodeproj/project.pbxproj
  litewallet/Assets.xcassets/Branding/launchLiteWalletImage.imageset/Contents.json
  litewallet/Assets.xcassets/Branding/launchLiteWalletImage.imageset/litewalletLaunchLogo.png
  litewallet/Assets.xcassets/Branding/litecoinFoundationLogo.imageset/Contents.json
  litewallet/Assets.xcassets/Branding/litecoinFoundationLogo.imageset/lfLaunchLogo.png
  litewallet/BartyCrouch.swift
  litewallet/Base.lproj/LaunchScreen.storyboard
  litewallet/Constants/Strings.swift
  litewallet/MainViewController.swift
  litewallet/ModalPresenter.swift
  litewallet/SeedViewModel.swift
  litewallet/SeedWordContainerView.swift
  litewallet/SeedWordView.swift
  litewallet/StartView.swift
  litewallet/StartViewModel.swift
  litewallet/Storyboards/Animate.storyboard
  litewallet/Strings/Base.lproj/Localizable.strings
  litewallet/Strings/da.lproj/Localizable.strings
  litewallet/Strings/de.lproj/Localizable.strings
  litewallet/Strings/en.lproj/Localizable.strings
  litewallet/Strings/es.lproj/Localizable.strings
  litewallet/Strings/fr.lproj/Localizable.strings
  litewallet/Strings/id.lproj/Localizable.strings
  litewallet/Strings/it.lproj/Localizable.strings
  litewallet/Strings/ja.lproj/Localizable.strings
  litewallet/Strings/ko.lproj/Localizable.strings
  litewallet/Strings/nl.lproj/Localizable.strings
  litewallet/Strings/pt.lproj/Localizable.strings
  litewallet/Strings/ru.lproj/Localizable.strings
  litewallet/Strings/sv.lproj/Localizable.strings
  litewallet/Strings/tr.lproj/Localizable.strings
  litewallet/Strings/uk.lproj/Localizable.strings
  litewallet/Strings/zh-Hans.lproj/Localizable.strings
  litewallet/Strings/zh-Hant.lproj/Localizable.strings
  litewallet/ViewControllers/ConfirmPaperPhraseViewController.swift
  litewallet/ViewControllers/WritePaperPhraseViewController.swift
  litewallet/src/StartView.swift
  litewallet/src/ViewControllers/ConfirmPaperPhraseViewController.swift
  litewallet/src/ViewControllers/WritePaperPhraseViewController.swift
  litewalletTests/Seed Word Tests/SeedWordsTests.swift
Labels: 🥳 feature

#261 ✨[Feature] Add appsflyer
  litewallet.xcodeproj/project.pbxproj
  litewallet/AppDelegate.swift
  litewallet/GoogleService-Info.plist
  litewallet/PartnerData.swift
Labels: 🥳 feature

#263 Fixed crash when using non-main thread to call SwiftUI
  litewallet/ModalPresenter.swift
  litewallet/StartFlowPresenter.swift
Labels: 🐛 bug

#265 ⚡️[Feature] Add remote config [deconflicted]
  .gitignore
  litewallet.xcodeproj/project.pbxproj
  litewallet/AppDelegate.swift
  litewallet/BRAPIClient+Wallet.swift
  litewallet/BuyView.swift
  litewallet/BuyWKWebViewController.swift
  litewallet/Constants/Constants+Events.swift
  litewallet/Environment.swift
  litewallet/RemoteConfigHelper.swift
  litewalletTests/APIManagerTests.swift
  litewalletTests/APITests.swift
Labels: 🥳 feature

#267 Fixed NSInternalInconsistencyException & Swift runtime failure: arithmetic overflow
  litewallet.xcodeproj/project.pbxproj
  litewallet/UInt64+SafeArithmetic.swift
  litewallet/ViewModels/Transaction.swift
  litewallet/Views/DefaultCurrencyViewController.swift
Labels: 🐛 bug
